version: "3.7"

services:
  web:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - api

  api:
    container_name: api
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    expose:
      - 8001
    restart: on-failure
